language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
os:
  - linux
  - osx

before_install:
  - ./test/before_install.sh

script:
  - node-gyp configure
  - node-gyp build
  - node ./test/index.js


