language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

before_install:
  - apt-get install libbluetooth-dev
  - npm install node-gyp
script: "./node_modules/.bin/node-gyp configure && ./node_modules/.bin/node-gyp build"

