language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

before_install:
  - apt-get install libbluetooth-dev
  - npm install node-gyp
  - export PATH=$PATH:./node_modules/.bin

script:
  - node-gyp configure
  - node-gyp build
  - node ./test/index.js

